version: '3'

volumes:
  postgres_db: {}
  redis_db: {}

networks:
  bridge:

services:
  postgres:
    image: postgres:15
    networks:
      - bridge
    environment:
      - POSTGRES_USER=irvankdhf
      - POSTGRES_PASSWORD=irvan123
      - POSTGRES_DB=point_of_sales_db
    ports:
      - "25432:5432"
    volumes:
      - "postgres_db:/var/lib/postgresql/data"
  redis:
    image: redis:7.2.1
    networks:
      - bridge
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26379:6379"
    volumes:
      - "redis_db:/data"
